import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import axios from 'axios';

// Components //
import Quote from '../components/Quote';
import AuthorQuote from '../components/AuthorQuote';
import Random from '../components/Random';
import Loader from '../components/Loader';

// Styles //
import styles from '../styles/pages/Home.module.scss';

// API //
const baseURL = `https://quote-garden.herokuapp.com/api/v3/quotes/random`;

export default function Home() {
    const [quote, setQuote] = useState(null);
    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        getRandomQuote();
    }, []);

    const getRandomQuote = async () => {
        setIsLoading(true);
        try {
            const { data } = await axios.get(baseURL);
            setQuote(data.data);
        } catch (error) {
            console.log(error);
        }
        setIsLoading(false);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Random onClick={getRandomQuote} />
                <div className={styles.wrapperQuote}>
                    {quote &&
                        quote.map(
                            ({ _id, quoteText, quoteAuthor, quoteGenre }) => (
                                <Quote key={_id} text={quoteText}>
                                    <AuthorQuote
                                        name={quoteAuthor}
                                        genre={quoteGenre}
                                    />
                                </Quote>
                            )
                        )}
                    {isLoading && <Loader />}
                </div>
            </main>
        </div>
    );
}
